---
- name: Configuration Nginx
  hosts: 192.168.1.94
  become: true
  gather_facts: yes
  become_user: root
  tasks:
    - name: Getting backend name from consul KV storage
      set_fact:
        version: "{{ lookup('consul_kv', 'version', host='192.168.1.94') | default('v2', true)  }}"
#      when: version | length > 0
    - name: Print Key version
      debug:
        msg: "version = {{ version }}"
    - name: Configure Nginx for consul-template
      include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_stream_template_enable: true
        nginx_config_stream_template:
          - template_file: stream/load-balancer.conf.ctmpl.j2
            conf_file_name: load-balancer.conf.ctmpl
            conf_file_location: /etc/nginx/conf.d
        nginx_config_cleanup: true
        nginx_config_cleanup_paths:
          - directory:
              - /etc/nginx/conf.d
              - /etc/nginx/sites-enabled
            recurse: false
        nginx_config_cleanup_files:
          - /etc/nginx/conf.d/default.conf
          - /etc/nginx/sites-enabled/000-default
