---
# File: site.yml - Example Consul site playbook

- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - ansible-consul


- name: Consul client-1 and service
  hosts: 192.168.1.91
  any_errors_fatal: true
  become: true
  become_user: root
  vars_files:
    - consul_services-1.yaml
  roles:
    - ansible-consul

- name: Consul client-2 and service
  hosts: 192.168.1.93
  any_errors_fatal: true
  become: true
  become_user: root
  vars_files:
    - consul_services-2.yaml
  roles:
    - ansible-consul      
      

- name: Install Nginx
  hosts: 192.168.1.91
  gather_facts: yes
  any_errors_fatal: true
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - ansible-role-nginx

- name: Install Consul Template
  hosts: 192.168.1.94
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - ansible-consul-template

