---
# File: site.yml - Example Consul site playbook

- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - ansible-consul


- name: Consul client and service
  hosts: 192.168.1.91
  any_errors_fatal: true
  become: true
  become_user: root
  vars_files:
    - consul_services.yaml
  roles:
    - ansible-consul

#- name: Install Nginx
#  hosts: 192.168.1.91
#  gather_facts: yes
#  any_errors_fatal: true
#  become: true
#  become_user: root
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
#  roles:
#    - ansible-role-nginx
